//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExport
{

  // Procedures 
  // Local procedures 
  public void gen_B_line (HObject ho_Image, out HObject ho_OrginLineB, HTuple hv_RowL, 
      HTuple hv_ColumnL, out HTuple hv_RowBeginB, out HTuple hv_ColBeginB, out HTuple hv_RowEndB, 
      out HTuple hv_ColEndB)
  {




    // Local iconic variables 

    HObject ho_ROI_B, ho_ImageReducedB, ho_RegionB;
    HObject ho_RegionBlosing2, ho_RegionBorderB, ho_ContourBs;
    HObject ho_ContourBsSplit, ho_SelectedContourBs, ho_UnionContourBs;
    HObject ho_SelectedContours, ho_SortedContourBs, ho_ObjectSelectedB;

    // Local control variables 

    HTuple hv_Number = new HTuple(), hv_NrC = new HTuple();
    HTuple hv_NcC = new HTuple(), hv_DistC = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_OrginLineB);
    HOperatorSet.GenEmptyObj(out ho_ROI_B);
    HOperatorSet.GenEmptyObj(out ho_ImageReducedB);
    HOperatorSet.GenEmptyObj(out ho_RegionB);
    HOperatorSet.GenEmptyObj(out ho_RegionBlosing2);
    HOperatorSet.GenEmptyObj(out ho_RegionBorderB);
    HOperatorSet.GenEmptyObj(out ho_ContourBs);
    HOperatorSet.GenEmptyObj(out ho_ContourBsSplit);
    HOperatorSet.GenEmptyObj(out ho_SelectedContourBs);
    HOperatorSet.GenEmptyObj(out ho_UnionContourBs);
    HOperatorSet.GenEmptyObj(out ho_SelectedContours);
    HOperatorSet.GenEmptyObj(out ho_SortedContourBs);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelectedB);
    hv_RowBeginB = new HTuple();
    hv_ColBeginB = new HTuple();
    hv_RowEndB = new HTuple();
    hv_ColEndB = new HTuple();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_ROI_B.Dispose();
    HOperatorSet.GenRectangle1(out ho_ROI_B, hv_RowL+540, hv_ColumnL-101.5, hv_RowL+563, 
        hv_ColumnL+90.5);
    }
    ho_ImageReducedB.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_ROI_B, out ho_ImageReducedB);
    ho_RegionB.Dispose();
    HOperatorSet.Threshold(ho_ImageReducedB, out ho_RegionB, -2200, -1500);
    ho_RegionBlosing2.Dispose();
    HOperatorSet.ClosingRectangle1(ho_RegionB, out ho_RegionBlosing2, 35, 1);
    ho_RegionBorderB.Dispose();
    HOperatorSet.Boundary(ho_RegionBlosing2, out ho_RegionBorderB, "inner");
    ho_ContourBs.Dispose();
    HOperatorSet.GenContourRegionXld(ho_RegionBorderB, out ho_ContourBs, "border");
    ho_ContourBsSplit.Dispose();
    HOperatorSet.SegmentContoursXld(ho_ContourBs, out ho_ContourBsSplit, "lines", 
        5, 1, 1);
    ho_SelectedContourBs.Dispose();
    HOperatorSet.SelectContoursXld(ho_ContourBsSplit, out ho_SelectedContourBs, "contour_length", 
        15, 2000, -0.5, 0.5);
    ho_UnionContourBs.Dispose();
    HOperatorSet.UnionCollinearContoursXld(ho_SelectedContourBs, out ho_UnionContourBs, 
        100, 5, 5, 0.5, "attr_keep");
    ho_SelectedContours.Dispose();
    HOperatorSet.SelectContoursXld(ho_UnionContourBs, out ho_SelectedContours, "contour_length", 
        50, 2000, -0.5, 0.5);
    ho_SortedContourBs.Dispose();
    HOperatorSet.SortContoursXld(ho_SelectedContours, out ho_SortedContourBs, "character", 
        "true", "row");
    hv_Number.Dispose();
    HOperatorSet.CountObj(ho_SortedContourBs, out hv_Number);
    ho_ObjectSelectedB.Dispose();
    HOperatorSet.SelectObj(ho_SortedContourBs, out ho_ObjectSelectedB, hv_Number);
    hv_RowBeginB.Dispose();hv_ColBeginB.Dispose();hv_RowEndB.Dispose();hv_ColEndB.Dispose();hv_NrC.Dispose();hv_NcC.Dispose();hv_DistC.Dispose();
    HOperatorSet.FitLineContourXld(ho_ObjectSelectedB, "drop", -1, 0, 5, 1, out hv_RowBeginB, 
        out hv_ColBeginB, out hv_RowEndB, out hv_ColEndB, out hv_NrC, out hv_NcC, 
        out hv_DistC);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_OrginLineB.Dispose();
    HOperatorSet.GenContourPolygonXld(out ho_OrginLineB, hv_RowBeginB.TupleConcat(
        hv_RowEndB), hv_ColBeginB.TupleConcat(hv_ColEndB));
    }
    ho_ROI_B.Dispose();
    ho_ImageReducedB.Dispose();
    ho_RegionB.Dispose();
    ho_RegionBlosing2.Dispose();
    ho_RegionBorderB.Dispose();
    ho_ContourBs.Dispose();
    ho_ContourBsSplit.Dispose();
    ho_SelectedContourBs.Dispose();
    ho_UnionContourBs.Dispose();
    ho_SelectedContours.Dispose();
    ho_SortedContourBs.Dispose();
    ho_ObjectSelectedB.Dispose();

    hv_Number.Dispose();
    hv_NrC.Dispose();
    hv_NcC.Dispose();
    hv_DistC.Dispose();

    return;
  }

  public void get_C_line (HObject ho_Image, out HObject ho_OrginLineC, HTuple hv_RowL, 
      HTuple hv_ColumnL, out HTuple hv_RowBeginC, out HTuple hv_ColBeginC, out HTuple hv_RowEndC, 
      out HTuple hv_ColEndC)
  {




    // Local iconic variables 

    HObject ho_ROI_C, ho_ImageReducedC, ho_RegionC;
    HObject ho_RegionClosing2, ho_RegionBorderC, ho_ContourCs;
    HObject ho_ContourCsSplit, ho_SelectedContourCs, ho_UnionContourCs;
    HObject ho_SortedContourCs, ho_ObjectSelectedC, ho_UnionContours1;

    // Local control variables 

    HTuple hv_NrC = new HTuple(), hv_NcC = new HTuple();
    HTuple hv_DistC = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_OrginLineC);
    HOperatorSet.GenEmptyObj(out ho_ROI_C);
    HOperatorSet.GenEmptyObj(out ho_ImageReducedC);
    HOperatorSet.GenEmptyObj(out ho_RegionC);
    HOperatorSet.GenEmptyObj(out ho_RegionClosing2);
    HOperatorSet.GenEmptyObj(out ho_RegionBorderC);
    HOperatorSet.GenEmptyObj(out ho_ContourCs);
    HOperatorSet.GenEmptyObj(out ho_ContourCsSplit);
    HOperatorSet.GenEmptyObj(out ho_SelectedContourCs);
    HOperatorSet.GenEmptyObj(out ho_UnionContourCs);
    HOperatorSet.GenEmptyObj(out ho_SortedContourCs);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelectedC);
    HOperatorSet.GenEmptyObj(out ho_UnionContours1);
    hv_RowBeginC = new HTuple();
    hv_ColBeginC = new HTuple();
    hv_RowEndC = new HTuple();
    hv_ColEndC = new HTuple();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_ROI_C.Dispose();
    HOperatorSet.GenRectangle1(out ho_ROI_C, hv_RowL-270, hv_ColumnL+490, hv_RowL+270, 
        hv_ColumnL+499);
    }

    ho_ImageReducedC.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_ROI_C, out ho_ImageReducedC);
    ho_RegionC.Dispose();
    HOperatorSet.Threshold(ho_ImageReducedC, out ho_RegionC, -2200, -600);
    ho_RegionClosing2.Dispose();
    HOperatorSet.ClosingRectangle1(ho_RegionC, out ho_RegionClosing2, 1, 5);
    ho_RegionBorderC.Dispose();
    HOperatorSet.Boundary(ho_RegionClosing2, out ho_RegionBorderC, "inner");
    ho_ContourCs.Dispose();
    HOperatorSet.GenContourRegionXld(ho_RegionBorderC, out ho_ContourCs, "border");
    ho_ContourCsSplit.Dispose();
    HOperatorSet.SegmentContoursXld(ho_ContourCs, out ho_ContourCsSplit, "lines", 
        5, 1, 1);
    ho_SelectedContourCs.Dispose();
    HOperatorSet.SelectContoursXld(ho_ContourCsSplit, out ho_SelectedContourCs, "contour_length", 
        20, 2000, -0.5, 0.5);
    ho_UnionContourCs.Dispose();
    HOperatorSet.UnionCollinearContoursXld(ho_SelectedContourCs, out ho_UnionContourCs, 
        100, 10, 10, 0.5, "attr_keep");
    ho_SelectedContourCs.Dispose();
    HOperatorSet.SelectContoursXld(ho_UnionContourCs, out ho_SelectedContourCs, "contour_length", 
        50, 2000, -0.5, 0.5);
    ho_SortedContourCs.Dispose();
    HOperatorSet.SortContoursXld(ho_SelectedContourCs, out ho_SortedContourCs, "character", 
        "true", "row");
    ho_ObjectSelectedC.Dispose();
    HOperatorSet.SelectObj(ho_SortedContourCs, out ho_ObjectSelectedC, 2);
    ho_UnionContours1.Dispose();
    HOperatorSet.UnionCollinearContoursXld(ho_ObjectSelectedC, out ho_UnionContours1, 
        1000, 20, 20, 0.5, "attr_keep");
    hv_RowBeginC.Dispose();hv_ColBeginC.Dispose();hv_RowEndC.Dispose();hv_ColEndC.Dispose();hv_NrC.Dispose();hv_NcC.Dispose();hv_DistC.Dispose();
    HOperatorSet.FitLineContourXld(ho_UnionContours1, "drop", -1, 0, 5, 1, out hv_RowBeginC, 
        out hv_ColBeginC, out hv_RowEndC, out hv_ColEndC, out hv_NrC, out hv_NcC, 
        out hv_DistC);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_OrginLineC.Dispose();
    HOperatorSet.GenContourPolygonXld(out ho_OrginLineC, hv_RowBeginC.TupleConcat(
        hv_RowEndC), hv_ColBeginC.TupleConcat(hv_ColEndC));
    }
    ho_ROI_C.Dispose();
    ho_ImageReducedC.Dispose();
    ho_RegionC.Dispose();
    ho_RegionClosing2.Dispose();
    ho_RegionBorderC.Dispose();
    ho_ContourCs.Dispose();
    ho_ContourCsSplit.Dispose();
    ho_SelectedContourCs.Dispose();
    ho_UnionContourCs.Dispose();
    ho_SortedContourCs.Dispose();
    ho_ObjectSelectedC.Dispose();
    ho_UnionContours1.Dispose();

    hv_NrC.Dispose();
    hv_NcC.Dispose();
    hv_DistC.Dispose();

    return;
  }

  public void get_ImageB (HObject ho_ProfileImageBW, out HObject ho_ImageNewB, out HObject ho_ImageBWToByte)
  {



    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImageBWConverted, ho_ImageBWScaled;
    HObject ho_ImageNewBWMirror, ho_ImageNewBWConvert, ho_ImageBWMirror;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageNewB);
    HOperatorSet.GenEmptyObj(out ho_ImageBWToByte);
    HOperatorSet.GenEmptyObj(out ho_ImageBWConverted);
    HOperatorSet.GenEmptyObj(out ho_ImageBWScaled);
    HOperatorSet.GenEmptyObj(out ho_ImageNewBWMirror);
    HOperatorSet.GenEmptyObj(out ho_ImageNewBWConvert);
    HOperatorSet.GenEmptyObj(out ho_ImageBWMirror);
    ho_ImageBWConverted.Dispose();
    HOperatorSet.ConvertImageType(ho_ProfileImageBW, out ho_ImageBWConverted, "int4");
    ho_ImageBWScaled.Dispose();
    HOperatorSet.ScaleImage(ho_ImageBWConverted, out ho_ImageBWScaled, 1, -32768);
    {
    HObject ExpTmpOutVar_0;
    HOperatorSet.ScaleImage(ho_ImageBWScaled, out ExpTmpOutVar_0, 1.6, 0);
    ho_ImageBWScaled.Dispose();
    ho_ImageBWScaled = ExpTmpOutVar_0;
    }
    //get_image_size (ImageBWScaled, WidthB, HeightB)
    //gen_image_const (ImageNewTempBW, 'int4', WidthB, HeightB)
    //for Index := 0 to HeightB-1 by 1
      //get_grayval (ImageBWScaled, gen_tuple_const(WidthB,Index), [0:WidthB-1], grayValueBefore)
      //grayValue := grayValueBefore[0:WidthB-1]-([0:WidthB-1]*kB+bB)
      //set_grayval (ImageNewTempBW, gen_tuple_const(WidthB,Index), [0:WidthB-1], grayValue)
    //endfor
    ho_ImageNewBWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ImageBWScaled, out ho_ImageNewBWMirror, "column");
    ho_ImageNewBWConvert.Dispose();
    HOperatorSet.ConvertImageType(ho_ImageNewBWMirror, out ho_ImageNewBWConvert, 
        "int2");
    ho_ImageNewB.Dispose();
    HOperatorSet.RotateImage(ho_ImageNewBWConvert, out ho_ImageNewB, 90, "constant");

    ho_ImageBWConverted.Dispose();
    HOperatorSet.ConvertImageType(ho_ProfileImageBW, out ho_ImageBWConverted, "byte");
    ho_ImageBWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ImageBWConverted, out ho_ImageBWMirror, "column");
    ho_ImageBWToByte.Dispose();
    HOperatorSet.RotateImage(ho_ImageBWMirror, out ho_ImageBWToByte, 90, "constant");

    ho_ImageBWConverted.Dispose();
    ho_ImageBWScaled.Dispose();
    ho_ImageNewBWMirror.Dispose();
    ho_ImageNewBWConvert.Dispose();
    ho_ImageBWMirror.Dispose();


    return;
  }

  public void get_ImageTL (HObject ho_ProfileImageTLW, out HObject ho_ImageNewTLW, 
      out HObject ho_ImageTLWToByte)
  {



    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImageTLWConverted, ho_ImageTLWScaled;
    HObject ho_ImageNewTLWMirror, ho_ImageNewTLWConvert, ho_ImageTLWMirror;
    HObject ho_ImageRotateTLW;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageNewTLW);
    HOperatorSet.GenEmptyObj(out ho_ImageTLWToByte);
    HOperatorSet.GenEmptyObj(out ho_ImageTLWConverted);
    HOperatorSet.GenEmptyObj(out ho_ImageTLWScaled);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTLWMirror);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTLWConvert);
    HOperatorSet.GenEmptyObj(out ho_ImageTLWMirror);
    HOperatorSet.GenEmptyObj(out ho_ImageRotateTLW);
    ho_ImageTLWConverted.Dispose();
    HOperatorSet.ConvertImageType(ho_ProfileImageTLW, out ho_ImageTLWConverted, "int4");
    ho_ImageTLWScaled.Dispose();
    HOperatorSet.ScaleImage(ho_ImageTLWConverted, out ho_ImageTLWScaled, 1, -32768);
    {
    HObject ExpTmpOutVar_0;
    HOperatorSet.ScaleImage(ho_ImageTLWScaled, out ExpTmpOutVar_0, 1.6, 0);
    ho_ImageTLWScaled.Dispose();
    ho_ImageTLWScaled = ExpTmpOutVar_0;
    }
    {
    HObject ExpTmpOutVar_0;
    HOperatorSet.ScaleImage(ho_ImageTLWScaled, out ExpTmpOutVar_0, 1, 225);
    ho_ImageTLWScaled.Dispose();
    ho_ImageTLWScaled = ExpTmpOutVar_0;
    }
    //get_image_size (ImageTLWScaled, WidthPITLW, HeightPITLW)
    //gen_image_const (ImageNewTempTLW, 'int4', WidthPITLW, HeightPITLW)
    //for Index := 0 to HeightPITLW-1 by 1
      //get_grayval (ImageTLWScaled, gen_tuple_const(WidthPITLW,Index), [0:WidthPITLW-1], grayValuePITLWBefore)
      //grayValuePITLW := grayValuePITLWBefore[0:WidthPITLW-1]-([0:WidthPITLW-1]*kTL+bTL)
      //set_grayval (ImageNewTempTLW, gen_tuple_const(WidthPITLW,Index), [0:WidthPITLW-1], grayValuePITLW)
    //endfor
    ho_ImageNewTLWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ImageTLWScaled, out ho_ImageNewTLWMirror, "column");
    ho_ImageNewTLWConvert.Dispose();
    HOperatorSet.ConvertImageType(ho_ImageNewTLWMirror, out ho_ImageNewTLWConvert, 
        "int2");
    ho_ImageNewTLW.Dispose();
    HOperatorSet.RotateImage(ho_ImageNewTLWConvert, out ho_ImageNewTLW, 90, "constant");

    ho_ImageTLWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ProfileImageTLW, out ho_ImageTLWMirror, "column");
    ho_ImageRotateTLW.Dispose();
    HOperatorSet.RotateImage(ho_ImageTLWMirror, out ho_ImageRotateTLW, 90, "constant");
    ho_ImageTLWToByte.Dispose();
    HOperatorSet.ConvertImageType(ho_ImageRotateTLW, out ho_ImageTLWToByte, "byte");

    ho_ImageTLWConverted.Dispose();
    ho_ImageTLWScaled.Dispose();
    ho_ImageNewTLWMirror.Dispose();
    ho_ImageNewTLWConvert.Dispose();
    ho_ImageTLWMirror.Dispose();
    ho_ImageRotateTLW.Dispose();


    return;
  }

  public void get_ImageTR (HObject ho_ProfileImageTRW, out HObject ho_ImageNewTRW, 
      out HObject ho_ImageTRWToByte)
  {



    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImagePITRWConverted, ho_ImageTRWScaled;
    HObject ho_ImageNewTRWConvert, ho_ImageNewTRWMirror, ho_ImageTRWMirror;
    HObject ho_ImageRotateTRM;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageNewTRW);
    HOperatorSet.GenEmptyObj(out ho_ImageTRWToByte);
    HOperatorSet.GenEmptyObj(out ho_ImagePITRWConverted);
    HOperatorSet.GenEmptyObj(out ho_ImageTRWScaled);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTRWConvert);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTRWMirror);
    HOperatorSet.GenEmptyObj(out ho_ImageTRWMirror);
    HOperatorSet.GenEmptyObj(out ho_ImageRotateTRM);
    ho_ImagePITRWConverted.Dispose();
    HOperatorSet.ConvertImageType(ho_ProfileImageTRW, out ho_ImagePITRWConverted, 
        "int4");
    ho_ImageTRWScaled.Dispose();
    HOperatorSet.ScaleImage(ho_ImagePITRWConverted, out ho_ImageTRWScaled, 1, -32768);
    {
    HObject ExpTmpOutVar_0;
    HOperatorSet.ScaleImage(ho_ImageTRWScaled, out ExpTmpOutVar_0, 1.6, 400);
    ho_ImageTRWScaled.Dispose();
    ho_ImageTRWScaled = ExpTmpOutVar_0;
    }
    //get_image_size (ImageTRWScaled, WidthPITRW, HeightPITRW)
    //gen_image_const (ImageNewTempTRW, 'int4', WidthPITRW, HeightPITRW)
    //for Index := 0 to HeightPITRW-1 by 1
      //get_grayval (ImageTRWScaled, gen_tuple_const(WidthPITRW,Index), [0:WidthPITRW-1], grayValuePITRWBefore)
      //grayValuePITRW := grayValuePITRWBefore[0:WidthPITRW-1]-([0:WidthPITRW-1]*kTR+bTR)
      //set_grayval (ImageNewTempTRW, gen_tuple_const(WidthPITRW,Index), [0:WidthPITRW-1], grayValuePITRW)
    //endfor
    ho_ImageNewTRWConvert.Dispose();
    HOperatorSet.ConvertImageType(ho_ImageTRWScaled, out ho_ImageNewTRWConvert, "int2");
    ho_ImageNewTRWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ImageNewTRWConvert, out ho_ImageNewTRWMirror, "column");
    ho_ImageNewTRW.Dispose();
    HOperatorSet.RotateImage(ho_ImageNewTRWMirror, out ho_ImageNewTRW, 90, "constant");

    ho_ImageTRWMirror.Dispose();
    HOperatorSet.MirrorImage(ho_ProfileImageTRW, out ho_ImageTRWMirror, "column");
    ho_ImageRotateTRM.Dispose();
    HOperatorSet.RotateImage(ho_ImageTRWMirror, out ho_ImageRotateTRM, 90, "constant");
    ho_ImageTRWToByte.Dispose();
    HOperatorSet.ConvertImageType(ho_ImageRotateTRM, out ho_ImageTRWToByte, "byte");
    ho_ImagePITRWConverted.Dispose();
    ho_ImageTRWScaled.Dispose();
    ho_ImageNewTRWConvert.Dispose();
    ho_ImageNewTRWMirror.Dispose();
    ho_ImageTRWMirror.Dispose();
    ho_ImageRotateTRM.Dispose();


    return;
  }

  public void get_ImageUP (HObject ho_ImageNewTRW, HObject ho_NewImageNewTLW, out HObject ho_ImageUP)
  {



    // Local iconic variables 

    HObject ho_Region, ho_ConnectedRegions, ho_SelectedRegions;
    HObject ho_RegionOpening, ho_RegionDilation, ho_RegionUnion;
    HObject ho_ImageReduced;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageUP);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionOpening);
    HOperatorSet.GenEmptyObj(out ho_RegionDilation);
    HOperatorSet.GenEmptyObj(out ho_RegionUnion);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    ho_Region.Dispose();
    HOperatorSet.Threshold(ho_ImageNewTRW, out ho_Region, -128000, -25500);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_Region, out ho_ConnectedRegions);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
        "and", 99577.5, 2000000);
    ho_RegionOpening.Dispose();
    HOperatorSet.OpeningCircle(ho_SelectedRegions, out ho_RegionOpening, 9);
    ho_RegionDilation.Dispose();
    HOperatorSet.DilationCircle(ho_RegionOpening, out ho_RegionDilation, 5);
    ho_RegionUnion.Dispose();
    HOperatorSet.Union1(ho_RegionDilation, out ho_RegionUnion);
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_NewImageNewTLW, ho_RegionUnion, out ho_ImageReduced
        );
    ho_ImageUP.Dispose();
    HOperatorSet.PaintGray(ho_ImageReduced, ho_ImageNewTRW, out ho_ImageUP);
    ho_Region.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_RegionOpening.Dispose();
    ho_RegionDilation.Dispose();
    ho_RegionUnion.Dispose();
    ho_ImageReduced.Dispose();


    return;
  }

  public void get_located_line (HObject ho_ImageNewTRW, HTuple hv_RowL, HTuple hv_ColumnL, 
      out HTuple hv_PhiStd)
  {




    // Local iconic variables 

    HObject ho_ROI_0, ho_ImageReduced, ho_RegionStd;
    HObject ho_RegionClosing, ho_RegionOpeningStd, ho_RegionBorderStd;
    HObject ho_ContourStds, ho_ContourStdsSplit, ho_SelectedContourStds;
    HObject ho_UnionContourStds, ho_SortedContourStds, ho_ObjectSelectedStd;
    HObject ho_ContourStd;

    // Local control variables 

    HTuple hv_RowBeginStd = new HTuple(), hv_ColBeginStd = new HTuple();
    HTuple hv_RowEndStd = new HTuple(), hv_ColEndStd = new HTuple();
    HTuple hv_NrC = new HTuple(), hv_NcC = new HTuple(), hv_DistC = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ROI_0);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_RegionStd);
    HOperatorSet.GenEmptyObj(out ho_RegionClosing);
    HOperatorSet.GenEmptyObj(out ho_RegionOpeningStd);
    HOperatorSet.GenEmptyObj(out ho_RegionBorderStd);
    HOperatorSet.GenEmptyObj(out ho_ContourStds);
    HOperatorSet.GenEmptyObj(out ho_ContourStdsSplit);
    HOperatorSet.GenEmptyObj(out ho_SelectedContourStds);
    HOperatorSet.GenEmptyObj(out ho_UnionContourStds);
    HOperatorSet.GenEmptyObj(out ho_SortedContourStds);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelectedStd);
    HOperatorSet.GenEmptyObj(out ho_ContourStd);
    hv_PhiStd = new HTuple();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_ROI_0.Dispose();
    HOperatorSet.GenRectangle1(out ho_ROI_0, hv_RowL-260, hv_ColumnL+165, hv_RowL+270, 
        hv_ColumnL+185);
    }
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_ImageNewTRW, ho_ROI_0, out ho_ImageReduced);
    ho_RegionStd.Dispose();
    HOperatorSet.Threshold(ho_ImageReduced, out ho_RegionStd, -2050, 4095);
    ho_RegionClosing.Dispose();
    HOperatorSet.ClosingRectangle1(ho_RegionStd, out ho_RegionClosing, 1, 15);

    ho_RegionOpeningStd.Dispose();
    HOperatorSet.OpeningRectangle1(ho_RegionClosing, out ho_RegionOpeningStd, 1, 
        10);

    ho_RegionBorderStd.Dispose();
    HOperatorSet.Boundary(ho_RegionOpeningStd, out ho_RegionBorderStd, "inner");
    ho_ContourStds.Dispose();
    HOperatorSet.GenContourRegionXld(ho_RegionBorderStd, out ho_ContourStds, "border");
    ho_ContourStdsSplit.Dispose();
    HOperatorSet.SegmentContoursXld(ho_ContourStds, out ho_ContourStdsSplit, "lines", 
        5, 1, 1);
    ho_SelectedContourStds.Dispose();
    HOperatorSet.SelectContoursXld(ho_ContourStdsSplit, out ho_SelectedContourStds, 
        "contour_length", 20, 2000, -0.5, 0.5);
    ho_UnionContourStds.Dispose();
    HOperatorSet.UnionCollinearContoursExtXld(ho_SelectedContourStds, out ho_UnionContourStds, 
        200, 7, 7, 0.5, 0, -1, 1, 1, 1, 1, 1, 0, "attr_keep");
    ho_SelectedContourStds.Dispose();
    HOperatorSet.SelectContoursXld(ho_UnionContourStds, out ho_SelectedContourStds, 
        "contour_length", 30, 2000, -0.5, 0.5);
    ho_SortedContourStds.Dispose();
    HOperatorSet.SortContoursXld(ho_SelectedContourStds, out ho_SortedContourStds, 
        "character", "true", "row");
    ho_ObjectSelectedStd.Dispose();
    HOperatorSet.SelectObj(ho_SortedContourStds, out ho_ObjectSelectedStd, 1);
    hv_RowBeginStd.Dispose();hv_ColBeginStd.Dispose();hv_RowEndStd.Dispose();hv_ColEndStd.Dispose();hv_NrC.Dispose();hv_NcC.Dispose();hv_DistC.Dispose();
    HOperatorSet.FitLineContourXld(ho_ObjectSelectedStd, "drop", 200, 2, 5, 1, out hv_RowBeginStd, 
        out hv_ColBeginStd, out hv_RowEndStd, out hv_ColEndStd, out hv_NrC, out hv_NcC, 
        out hv_DistC);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_ContourStd.Dispose();
    HOperatorSet.GenContourPolygonXld(out ho_ContourStd, hv_RowBeginStd.TupleConcat(
        hv_RowEndStd), hv_ColBeginStd.TupleConcat(hv_ColEndStd));
    }

    hv_PhiStd.Dispose();
    HOperatorSet.LineOrientation(hv_RowBeginStd, hv_ColBeginStd, hv_RowEndStd, hv_ColEndStd, 
        out hv_PhiStd);
    ho_ROI_0.Dispose();
    ho_ImageReduced.Dispose();
    ho_RegionStd.Dispose();
    ho_RegionClosing.Dispose();
    ho_RegionOpeningStd.Dispose();
    ho_RegionBorderStd.Dispose();
    ho_ContourStds.Dispose();
    ho_ContourStdsSplit.Dispose();
    ho_SelectedContourStds.Dispose();
    ho_UnionContourStds.Dispose();
    ho_SortedContourStds.Dispose();
    ho_ObjectSelectedStd.Dispose();
    ho_ContourStd.Dispose();

    hv_RowBeginStd.Dispose();
    hv_ColBeginStd.Dispose();
    hv_RowEndStd.Dispose();
    hv_ColEndStd.Dispose();
    hv_NrC.Dispose();
    hv_NcC.Dispose();
    hv_DistC.Dispose();

    return;
  }

  public void get_location (HObject ho_ProfileImageTLW, HObject ho_ProfileImageTRW, 
      HObject ho_ProfileImageBW, out HObject ho_ImageNewTLW, out HObject ho_ImageNewTRW, 
      out HObject ho_ImageNewBW, out HObject ho_fit_contour, out HObject ho_ImageUP, 
      HTuple hv_ModelID, out HTuple hv_RowB, out HTuple hv_ColB, out HTuple hv_RowC, 
      out HTuple hv_ColC)
  {




    // Local iconic variables 

    HObject ho_ImageNewTL, ho_ImageTLWToByte, ho_ImageTRWToByte;
    HObject ho_ImageNewB, ho_ImageBWToByte, ho_ROI_0, ho_ImageReducedMS;
    HObject ho_ModelImages, ho_ModelRegions, ho_OrginLineB;
    HObject ho_LineB, ho_OrginLineC, ho_LineC;

    // Local control variables 

    HTuple hv_RowTLW = new HTuple(), hv_ColumnTLW = new HTuple();
    HTuple hv_AngleTLW = new HTuple(), hv_ScoreTLW = new HTuple();
    HTuple hv_ModelIDMS = new HTuple(), hv_RowTR = new HTuple();
    HTuple hv_ColumnTR = new HTuple(), hv_AngleTR = new HTuple();
    HTuple hv_ScoreTR = new HTuple(), hv_RowTL = new HTuple();
    HTuple hv_ColumnTL = new HTuple(), hv_AngleTL = new HTuple();
    HTuple hv_ScoreTL = new HTuple(), hv_HomMat2D = new HTuple();
    HTuple hv_AngleB = new HTuple(), hv_Score2 = new HTuple();
    HTuple hv_PhiStd = new HTuple(), hv_RowBeginB = new HTuple();
    HTuple hv_ColBeginB = new HTuple(), hv_RowEndB = new HTuple();
    HTuple hv_ColEndB = new HTuple(), hv_HomMat2DB = new HTuple();
    HTuple hv_PhiBB = new HTuple(), hv_RowBeginC = new HTuple();
    HTuple hv_ColBeginC = new HTuple(), hv_RowEndC = new HTuple();
    HTuple hv_ColEndC = new HTuple(), hv_PhiC = new HTuple();
    HTuple hv_HomMat2DC = new HTuple(), hv_PhiCC = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageNewTLW);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTRW);
    HOperatorSet.GenEmptyObj(out ho_ImageNewBW);
    HOperatorSet.GenEmptyObj(out ho_fit_contour);
    HOperatorSet.GenEmptyObj(out ho_ImageUP);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTL);
    HOperatorSet.GenEmptyObj(out ho_ImageTLWToByte);
    HOperatorSet.GenEmptyObj(out ho_ImageTRWToByte);
    HOperatorSet.GenEmptyObj(out ho_ImageNewB);
    HOperatorSet.GenEmptyObj(out ho_ImageBWToByte);
    HOperatorSet.GenEmptyObj(out ho_ROI_0);
    HOperatorSet.GenEmptyObj(out ho_ImageReducedMS);
    HOperatorSet.GenEmptyObj(out ho_ModelImages);
    HOperatorSet.GenEmptyObj(out ho_ModelRegions);
    HOperatorSet.GenEmptyObj(out ho_OrginLineB);
    HOperatorSet.GenEmptyObj(out ho_LineB);
    HOperatorSet.GenEmptyObj(out ho_OrginLineC);
    HOperatorSet.GenEmptyObj(out ho_LineC);
    hv_RowB = new HTuple();
    hv_ColB = new HTuple();
    hv_RowC = new HTuple();
    hv_ColC = new HTuple();
    //****************矫正I40TL照片
    ho_ImageNewTL.Dispose();ho_ImageTLWToByte.Dispose();
    get_ImageTL(ho_ProfileImageTLW, out ho_ImageNewTL, out ho_ImageTLWToByte);
    //矫正I40TR照片
    ho_ImageNewTRW.Dispose();ho_ImageTRWToByte.Dispose();
    get_ImageTR(ho_ProfileImageTRW, out ho_ImageNewTRW, out ho_ImageTRWToByte);
    //****************矫正I40B照片
    ho_ImageNewB.Dispose();ho_ImageBWToByte.Dispose();
    get_ImageB(ho_ProfileImageBW, out ho_ImageNewB, out ho_ImageBWToByte);
    //**********************合并上面两张图

    //针对每个工件正反面定位
    hv_RowTLW.Dispose();hv_ColumnTLW.Dispose();hv_AngleTLW.Dispose();hv_ScoreTLW.Dispose();
    HOperatorSet.FindShapeModel(ho_ImageTRWToByte, hv_ModelID, -0.39, 0.79, 0.3, 
        1, 0.5, "least_squares", 0, 0.9, out hv_RowTLW, out hv_ColumnTLW, out hv_AngleTLW, 
        out hv_ScoreTLW);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_ROI_0.Dispose();
    HOperatorSet.GenRectangle1(out ho_ROI_0, hv_RowTLW-485, hv_ColumnTLW-80, hv_RowTLW+480, 
        hv_ColumnTLW+80);
    }
    ho_ImageReducedMS.Dispose();
    HOperatorSet.ReduceDomain(ho_ImageTRWToByte, ho_ROI_0, out ho_ImageReducedMS);
    ho_ModelImages.Dispose();ho_ModelRegions.Dispose();
    HOperatorSet.InspectShapeModel(ho_ImageReducedMS, out ho_ModelImages, out ho_ModelRegions, 
        4, 50);
    hv_ModelIDMS.Dispose();
    HOperatorSet.CreateShapeModel(ho_ImageReducedMS, 4, -0.39, 0.79, "auto", "auto", 
        "use_polarity", "auto", "auto", out hv_ModelIDMS);
    //找模板，找旋转中心
    hv_RowTR.Dispose();hv_ColumnTR.Dispose();hv_AngleTR.Dispose();hv_ScoreTR.Dispose();
    HOperatorSet.FindShapeModel(ho_ImageTRWToByte, hv_ModelIDMS, -1, 1, 0.5, 1, 0.5, 
        "least_squares", 2, 0.9, out hv_RowTR, out hv_ColumnTR, out hv_AngleTR, out hv_ScoreTR);
    //dev_display (ImageTRWToByte)
    //dev_display_shape_matching_results (ModelID, 'red', RowTR, ColumnTR, AngleTR, 1, 1, 0)
    hv_RowTL.Dispose();hv_ColumnTL.Dispose();hv_AngleTL.Dispose();hv_ScoreTL.Dispose();
    HOperatorSet.FindShapeModel(ho_ImageTLWToByte, hv_ModelIDMS, -1, 1, 0.3, 1, 0.5, 
        "least_squares", 2, 0.9, out hv_RowTL, out hv_ColumnTL, out hv_AngleTL, out hv_ScoreTL);
    //dev_display (ImageTLWToByte)
    //dev_display_shape_matching_results (ModelID, 'red', RowTL, ColumnTL, AngleTL, 1, 1, 0)
    //旋转TL矫正镜像图片照片
    hv_HomMat2D.Dispose();
    HOperatorSet.VectorAngleToRigid(hv_RowTL, hv_ColumnTL, hv_AngleTL, hv_RowTR, 
        hv_ColumnTR, hv_AngleTR, out hv_HomMat2D);
    ho_ImageNewTLW.Dispose();
    HOperatorSet.AffineTransImage(ho_ImageNewTL, out ho_ImageNewTLW, hv_HomMat2D, 
        "constant", "false");
    ho_ImageUP.Dispose();
    get_ImageUP(ho_ImageNewTRW, ho_ImageNewTLW, out ho_ImageUP);
    //底面旋转到检测位置
    hv_RowB.Dispose();hv_ColB.Dispose();hv_AngleB.Dispose();hv_Score2.Dispose();
    HOperatorSet.FindShapeModel(ho_ImageBWToByte, hv_ModelID, -1, 1, 0.2, 1, 0.5, 
        "least_squares", 2, 0.9, out hv_RowB, out hv_ColB, out hv_AngleB, out hv_Score2);
    //dev_display (ImageRotateB)
    //dev_display_shape_matching_results (ModelID, 'red', RowB, ColB, AngleB, 1, 1, 0)
    hv_HomMat2D.Dispose();
    HOperatorSet.VectorAngleToRigid(hv_RowB, hv_ColB, hv_AngleB, hv_RowTL, hv_ColumnTL, 
        hv_AngleTL, out hv_HomMat2D);
    ho_ImageNewBW.Dispose();
    HOperatorSet.AffineTransImage(ho_ImageNewB, out ho_ImageNewBW, hv_HomMat2D, "constant", 
        "false");

    //创建模板
    //gen_rectangle1 (ROI_0, 237.934, 181.275, 1140.4, 306.398)
    //reduce_domain (ImageTLWToByte, ROI_0, ImageReducedMS)
    //inspect_shape_model (ImageReducedMS, ModelImages, ModelRegions, 4, 50)
    //create_shape_model (ImageReducedMS, 4, -0.39, 0.79, 'auto', 'auto', 'use_polarity', 'auto', 'auto', ModelIDL)
    //找模板，找旋转中心
    //find_shape_model (ImageTLWToByte, ModelIDMS, -1, 1, 0.5, 1, 0.3, 'least_squares', 2, 0.9, RowL, ColumnL, AngleL, ScoreTL)
    //dev_display (ImageTLWToByte)
    //dev_display_shape_matching_results (ModelID, 'red', RowTL, ColumnTL, AngleTL, 1, 1, 0)
    //获取定位线
    hv_PhiStd.Dispose();
    get_located_line(ho_ImageNewTRW, hv_RowTR, hv_ColumnTR, out hv_PhiStd);
    //生成基准垂线
    //RowM := (RowBeginStd+RowEndStd)/2
    //ColM := (ColBeginStd+ColEndStd)/2
    //********************生成垂线**************************垂线长度
    //LineLength := 200
    //起点
    //RowStartV := RowM-cos(PhiStd)*LineLength
    //ColStartV := ColM-sin(PhiStd)*LineLength
    //终点
    //RowEndV := RowM+cos(PhiStd)*LineLength
    //ColEndV := ColM+sin(PhiStd)
    //LineLength
    //line_orientation (RowStartV, RowStartV, RowEndV, ColEndV, PhiV)
    //gen_contour_polygon_xld (ContourV, [RowStartV,RowEndV], [ColStartV,ColEndV])

    //生成B条线
    ho_OrginLineB.Dispose();hv_RowBeginB.Dispose();hv_ColBeginB.Dispose();hv_RowEndB.Dispose();hv_ColEndB.Dispose();
    gen_B_line(ho_ImageNewTRW, out ho_OrginLineB, hv_RowTR, hv_ColumnTR, out hv_RowBeginB, 
        out hv_ColBeginB, out hv_RowEndB, out hv_ColEndB);
    //校准B线
    hv_RowB.Dispose();
    HOperatorSet.LineOrientation(hv_RowBeginB, hv_ColBeginB, hv_RowEndB, hv_ColEndB, 
        out hv_RowB);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_HomMat2DB.Dispose();
    HOperatorSet.VectorAngleToRigid((hv_RowBeginB+hv_RowEndB)/2, (hv_ColBeginB+hv_ColEndB)/2, 
        hv_RowB, (hv_RowBeginB+hv_RowEndB)/2, (hv_ColBeginB+hv_ColEndB)/2, hv_PhiStd-((new HTuple(90)).TupleRad()
        ), out hv_HomMat2DB);
    }
    ho_LineB.Dispose();
    HOperatorSet.AffineTransContourXld(ho_OrginLineB, out ho_LineB, hv_HomMat2DB);
    hv_RowB.Dispose();hv_ColB.Dispose();
    HOperatorSet.GetContourXld(ho_LineB, out hv_RowB, out hv_ColB);
    hv_PhiBB.Dispose();
    HOperatorSet.OrientationXld(ho_LineB, out hv_PhiBB);
    //生成C条线
    ho_OrginLineC.Dispose();hv_RowBeginC.Dispose();hv_ColBeginC.Dispose();hv_RowEndC.Dispose();hv_ColEndC.Dispose();
    get_C_line(ho_ImageNewTRW, out ho_OrginLineC, hv_RowTR, hv_ColumnTR, out hv_RowBeginC, 
        out hv_ColBeginC, out hv_RowEndC, out hv_ColEndC);
    //校准C线
    hv_PhiC.Dispose();
    HOperatorSet.LineOrientation(hv_RowBeginC, hv_ColBeginC, hv_RowEndC, hv_ColEndC, 
        out hv_PhiC);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_HomMat2DC.Dispose();
    HOperatorSet.VectorAngleToRigid((hv_RowBeginC+hv_RowEndC)/2, (hv_ColBeginC+hv_ColEndC)/2, 
        hv_PhiC, (hv_RowBeginC+hv_RowEndC)/2, (hv_ColBeginC+hv_ColEndC)/2, hv_PhiStd, 
        out hv_HomMat2DC);
    }
    ho_LineC.Dispose();
    HOperatorSet.AffineTransContourXld(ho_OrginLineC, out ho_LineC, hv_HomMat2DC);
    hv_RowC.Dispose();hv_ColC.Dispose();
    HOperatorSet.GetContourXld(ho_LineC, out hv_RowC, out hv_ColC);
    hv_PhiCC.Dispose();
    HOperatorSet.OrientationXld(ho_LineC, out hv_PhiCC);
    ho_fit_contour.Dispose();
    HOperatorSet.GenEmptyObj(out ho_fit_contour);
    //concat_obj (fit_contour, ObjectSelectedC, fit_contour)
    //concat_obj (fit_contour, ObjectSelectedB, fit_contour)
    //concat_obj (fit_contour, ObjectSelectedStd, fit_contour)
    ho_ImageNewTL.Dispose();
    ho_ImageTLWToByte.Dispose();
    ho_ImageTRWToByte.Dispose();
    ho_ImageNewB.Dispose();
    ho_ImageBWToByte.Dispose();
    ho_ROI_0.Dispose();
    ho_ImageReducedMS.Dispose();
    ho_ModelImages.Dispose();
    ho_ModelRegions.Dispose();
    ho_OrginLineB.Dispose();
    ho_LineB.Dispose();
    ho_OrginLineC.Dispose();
    ho_LineC.Dispose();

    hv_RowTLW.Dispose();
    hv_ColumnTLW.Dispose();
    hv_AngleTLW.Dispose();
    hv_ScoreTLW.Dispose();
    hv_ModelIDMS.Dispose();
    hv_RowTR.Dispose();
    hv_ColumnTR.Dispose();
    hv_AngleTR.Dispose();
    hv_ScoreTR.Dispose();
    hv_RowTL.Dispose();
    hv_ColumnTL.Dispose();
    hv_AngleTL.Dispose();
    hv_ScoreTL.Dispose();
    hv_HomMat2D.Dispose();
    hv_AngleB.Dispose();
    hv_Score2.Dispose();
    hv_PhiStd.Dispose();
    hv_RowBeginB.Dispose();
    hv_ColBeginB.Dispose();
    hv_RowEndB.Dispose();
    hv_ColEndB.Dispose();
    hv_HomMat2DB.Dispose();
    hv_PhiBB.Dispose();
    hv_RowBeginC.Dispose();
    hv_ColBeginC.Dispose();
    hv_RowEndC.Dispose();
    hv_ColEndC.Dispose();
    hv_PhiC.Dispose();
    hv_HomMat2DC.Dispose();
    hv_PhiCC.Dispose();

    return;
  }

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_ProfileImageTLW=null, ho_ProfileImageTRW=null;
    HObject ho_ProfileImageBW=null, ho_ImageNewTLW=null, ho_ImageNewTRW=null;
    HObject ho_ImageNewBW=null, ho_fit_contour=null, ho_ImageUP=null;
    HObject ho_ImageUPShow=null, ho_Contourb=null, ho_Contourc=null;

    // Local control variables 

    HTuple hv_FileHandleData = new HTuple(), hv_ImageFilesTL = new HTuple();
    HTuple hv_ImageFilesTR = new HTuple(), hv_ImageFilesB = new HTuple();
    HTuple hv_IndexLoop = new HTuple(), hv_ModelID = new HTuple();
    HTuple hv_RowB = new HTuple(), hv_ColB = new HTuple();
    HTuple hv_RowC = new HTuple(), hv_ColC = new HTuple();
    HTuple hv_Row1 = new HTuple(), hv_Column1 = new HTuple();
    HTuple hv_IsOverlapping1 = new HTuple(), hv_Row2 = new HTuple();
    HTuple hv_Column2 = new HTuple(), hv_Row3 = new HTuple();
    HTuple hv_Column3 = new HTuple(), hv_Row4 = new HTuple();
    HTuple hv_Column4 = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ProfileImageTLW);
    HOperatorSet.GenEmptyObj(out ho_ProfileImageTRW);
    HOperatorSet.GenEmptyObj(out ho_ProfileImageBW);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTLW);
    HOperatorSet.GenEmptyObj(out ho_ImageNewTRW);
    HOperatorSet.GenEmptyObj(out ho_ImageNewBW);
    HOperatorSet.GenEmptyObj(out ho_fit_contour);
    HOperatorSet.GenEmptyObj(out ho_ImageUP);
    HOperatorSet.GenEmptyObj(out ho_ImageUPShow);
    HOperatorSet.GenEmptyObj(out ho_Contourb);
    HOperatorSet.GenEmptyObj(out ho_Contourc);
    hv_FileHandleData.Dispose();
    HOperatorSet.OpenFile("C:/Users/25001885/Desktop/data.csv", "output", out hv_FileHandleData);
    hv_ImageFilesTL.Dispose();
    HOperatorSet.ListFiles("G:/项目文件/1102/MTM/2", (new HTuple("files")).TupleConcat(
        "follow_links"), out hv_ImageFilesTL);
    {
    HTuple ExpTmpOutVar_0;
    HOperatorSet.TupleRegexpSelect(hv_ImageFilesTL, (new HTuple("\\.(tif|tiff|gif|bmp|jpg|jpeg|jp2|png|pcx|pgm|ppm|pbm|xwd|ima|hobj)$")).TupleConcat(
        "ignore_case"), out ExpTmpOutVar_0);
    hv_ImageFilesTL.Dispose();
    hv_ImageFilesTL = ExpTmpOutVar_0;
    }
    hv_ImageFilesTR.Dispose();
    HOperatorSet.ListFiles("G:/项目文件/1102/MTM/3", (new HTuple("files")).TupleConcat(
        "follow_links"), out hv_ImageFilesTR);
    {
    HTuple ExpTmpOutVar_0;
    HOperatorSet.TupleRegexpSelect(hv_ImageFilesTR, (new HTuple("\\.(tif|tiff|gif|bmp|jpg|jpeg|jp2|png|pcx|pgm|ppm|pbm|xwd|ima|hobj)$")).TupleConcat(
        "ignore_case"), out ExpTmpOutVar_0);
    hv_ImageFilesTR.Dispose();
    hv_ImageFilesTR = ExpTmpOutVar_0;
    }
    hv_ImageFilesB.Dispose();
    HOperatorSet.ListFiles("G:/项目文件/1102/MTM/1", (new HTuple("files")).TupleConcat(
        "follow_links"), out hv_ImageFilesB);
    {
    HTuple ExpTmpOutVar_0;
    HOperatorSet.TupleRegexpSelect(hv_ImageFilesB, (new HTuple("\\.(tif|tiff|gif|bmp|jpg|jpeg|jp2|png|pcx|pgm|ppm|pbm|xwd|ima|hobj)$")).TupleConcat(
        "ignore_case"), out ExpTmpOutVar_0);
    hv_ImageFilesB.Dispose();
    hv_ImageFilesB = ExpTmpOutVar_0;
    }
    for (hv_IndexLoop=0; (int)hv_IndexLoop<=(int)((new HTuple(hv_ImageFilesB.TupleLength()
        ))-1); hv_IndexLoop = (int)hv_IndexLoop + 1)
    {
      //dev_update_off ()
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_ProfileImageTLW.Dispose();
      HOperatorSet.ReadImage(out ho_ProfileImageTLW, hv_ImageFilesTL.TupleSelect(
          hv_IndexLoop));
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_ProfileImageTRW.Dispose();
      HOperatorSet.ReadImage(out ho_ProfileImageTRW, hv_ImageFilesTR.TupleSelect(
          hv_IndexLoop));
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_ProfileImageBW.Dispose();
      HOperatorSet.ReadImage(out ho_ProfileImageBW, hv_ImageFilesB.TupleSelect(hv_IndexLoop));
      }
      //创建模板,初定位
      hv_ModelID.Dispose();
      HOperatorSet.ReadShapeModel("G:/项目文件/1106/model", out hv_ModelID);
      ho_ImageNewTLW.Dispose();ho_ImageNewTRW.Dispose();ho_ImageNewBW.Dispose();ho_fit_contour.Dispose();ho_ImageUP.Dispose();hv_RowB.Dispose();hv_ColB.Dispose();hv_RowC.Dispose();hv_ColC.Dispose();
      get_location(ho_ProfileImageTLW, ho_ProfileImageTRW, ho_ProfileImageBW, out ho_ImageNewTLW, 
          out ho_ImageNewTRW, out ho_ImageNewBW, out ho_fit_contour, out ho_ImageUP, 
          hv_ModelID, out hv_RowB, out hv_ColB, out hv_RowC, out hv_ColC);
      ho_ImageUPShow.Dispose();
      HOperatorSet.ScaleImage(ho_ImageUP, out ho_ImageUPShow, 0.001, 0);
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Row1.Dispose();hv_Column1.Dispose();hv_IsOverlapping1.Dispose();
      HOperatorSet.IntersectionLines(hv_RowB.TupleSelect(0), hv_ColB.TupleSelect(
          0), hv_RowB.TupleSelect(1), hv_ColB.TupleSelect(1), 0, 0, 1600, 0, out hv_Row1, 
          out hv_Column1, out hv_IsOverlapping1);
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Row2.Dispose();hv_Column2.Dispose();hv_IsOverlapping1.Dispose();
      HOperatorSet.IntersectionLines(hv_RowB.TupleSelect(0), hv_ColB.TupleSelect(
          0), hv_RowB.TupleSelect(1), hv_ColB.TupleSelect(1), 0, 800, 1600, 800, 
          out hv_Row2, out hv_Column2, out hv_IsOverlapping1);
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_Contourb.Dispose();
      HOperatorSet.GenContourPolygonXld(out ho_Contourb, hv_Row1.TupleConcat(hv_Row2), 
          hv_Column1.TupleConcat(hv_Column2));
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Row3.Dispose();hv_Column3.Dispose();hv_IsOverlapping1.Dispose();
      HOperatorSet.IntersectionLines(0, 0, 0, 800, hv_RowC.TupleSelect(0), hv_ColC.TupleSelect(
          0), hv_RowC.TupleSelect(1), hv_ColC.TupleSelect(1), out hv_Row3, out hv_Column3, 
          out hv_IsOverlapping1);
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Row4.Dispose();hv_Column4.Dispose();hv_IsOverlapping1.Dispose();
      HOperatorSet.IntersectionLines(1600, 0, 1600, 800, hv_RowC.TupleSelect(0), 
          hv_ColC.TupleSelect(0), hv_RowC.TupleSelect(1), hv_ColC.TupleSelect(1), 
          out hv_Row4, out hv_Column4, out hv_IsOverlapping1);
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_Contourc.Dispose();
      HOperatorSet.GenContourPolygonXld(out ho_Contourc, hv_Row3.TupleConcat(hv_Row4), 
          hv_Column3.TupleConcat(hv_Column4));
      }
      //dev_update_on ()
      //dev_display (ImageUPShow)
      //dev_display (Contourc)
      //dev_display (Contourb)
    }
    ho_ProfileImageTLW.Dispose();
    ho_ProfileImageTRW.Dispose();
    ho_ProfileImageBW.Dispose();
    ho_ImageNewTLW.Dispose();
    ho_ImageNewTRW.Dispose();
    ho_ImageNewBW.Dispose();
    ho_fit_contour.Dispose();
    ho_ImageUP.Dispose();
    ho_ImageUPShow.Dispose();
    ho_Contourb.Dispose();
    ho_Contourc.Dispose();

    hv_FileHandleData.Dispose();
    hv_ImageFilesTL.Dispose();
    hv_ImageFilesTR.Dispose();
    hv_ImageFilesB.Dispose();
    hv_IndexLoop.Dispose();
    hv_ModelID.Dispose();
    hv_RowB.Dispose();
    hv_ColB.Dispose();
    hv_RowC.Dispose();
    hv_ColC.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_IsOverlapping1.Dispose();
    hv_Row2.Dispose();
    hv_Column2.Dispose();
    hv_Row3.Dispose();
    hv_Column3.Dispose();
    hv_Row4.Dispose();
    hv_Column4.Dispose();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

